### ISSUE TITLE
To Insert the designers for they contribute with creating new tokens

### ISSUE THREAD

**Issue by emanuelcaaju** [Xcov19/mhc-fe#29]
Akul (@codecakes), in order for all designers to be able to use the tokens, it is necessary to include them as contributors to the Design_Tokens branch. Without this insertion, they can only consume the tokens, and cannot perform new updates by creating new tokens. I started contacting the team looking to make the 1:1 but this point has been a block so that they can use the Tokens to their fullest.

The users that need to be entered are formalized below:

@mattschabel
@isidoravladic
@gabylopezc
@kazz24

**Comment by codecakes** [comment]
All tokens and changes can be added in a new PR.

Every contributor can raise a new PR following the guidelines you have mentioned in your README Branch under the section heading: **How to integrate figma, figma token to this repository**

Each PR branch = Individual Changes.
Contributors never should require to mess other branches.

If this is not clear reopen this issue.
